## name: dfsdfs_tb.fdo
## Created on: Wed Jul 26 03:31:03 PM CEST 2017
##
##  Auto generated by Project Navigator for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the project directory and will not be removed on
##  subsequent simulation flows run from Project Navigator.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#
# Create work library
#
file delete -force work
vlib work
#
# Compile sources
#
vlog -novopt ../hdl/rx_uart.v
#vlog -novopt ../hdl/tx_uart.v
#vlog -novopt ../hdl/tx_uart_fsm.v
vlog -novopt tx_uart_tb.v
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps  -lib work work.tx_uart_tb
#
# Source the wave do file
#
#####do {dfsdfs_tb_wave.fdo}
##add wave *
#
# Set the window types
#
view wave
view structure
view signals
#
# Source the user do file
#
##add wave *
#
# Run simulation for this time
#
run 220 us
#
# End
